name: bochemian
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scipy
  - pytorch
  - scikit-learn
  - scikit-learn-extra
  - pre_commit
  - pytorch-lightning
  - wandb
  - gpytorch
  - matplotlib
  - pip:
    - -e .
    # - -e ../gauche
    - rxnfp --no-deps
    - drfp
    - transformers
    - jsonargparse[signatures]
    - graphein==1.5.1
    - torch-geometric==1.7.2
dev_dependencies:
  - pre-commit
  - tox
  - black
  - isort
  - flake8
  - sphinx
  - coverage
